'use strict';
const $=id=>document.getElementById(id);
let phase=0,score=0,attempts=0,solved=false,remaining=120,timer=null,paused=false,px=3,py=5;
const stages=[
 {name:'A queda',eyebrow:'PREPARE O POUSO',title:'Cada coordenada,<br>um novo destino.',sprite:'assets/parachute.svg',map:'TERRENO • h(x, y) = x² + y²',body:'Escolha as coordenadas e calcule a altitude antes de saltar. O primeiro pouso sugerido é (3, 5).',formula:'h(x, y) = x² + y²',fields:'<label>Coordenada x<input id="x" type="number" min="-5" max="5" step="1" value="3" required></label><label>Coordenada y<input id="y" type="number" min="-5" max="5" step="1" value="5" required></label><label class="wide">Altitude h(x, y)<input id="a" inputmode="decimal" autocomplete="off" required></label>',button:'Confirmar pouso',hint:'Substitua x e y na função. Eleve cada coordenada ao quadrado e depois some.'},
 {name:'Construindo a base',eyebrow:'NIVELE A PLATAFORMA',title:'Uma base firme.<br>Um plano preciso.',sprite:'assets/wall.svg',map:'SUPERFÍCIE • f(x, y) = x² + 2y²',body:'Para f(x, y) = x² + 2y², construa uma plataforma tangente em (1, 2). Escreva o plano na forma z = Ax + By + C, preenchendo os coeficientes.',formula:'z = f(a,b) + fₓ(a,b)(x − a)<br>+ fᵧ(a,b)(y − b)',fields:'<label>A<input id="a" inputmode="decimal" required></label><label>B<input id="b" inputmode="decimal" required></label><label>C<input id="c" inputmode="decimal" required></label>',button:'Construir plataforma',hint:'fₓ = 2x e fᵧ = 4y. Calcule essas derivadas e a altura em (1, 2); depois expanda o plano.'},
 {name:'A tempestade se aproxima',eyebrow:'ACOMPANHE A TEMPESTADE',title:'O tempo muda.<br>Você prevê.',sprite:'assets/cloud-lightning.svg',map:'CAMPO • T(x, y) = 3x + 2y',body:'Para T(x, y) = 3x + 2y, ao longo da trajetória x(t) = t² e y(t) = 3t, calcule dT/dt em t = 2. O relógio é um desafio opcional: você pode pausar e continuar estudando.',formula:'dT/dt = Tₓ · dx/dt + Tᵧ · dy/dt',fields:'<label class="wide">Taxa de mudança em t = 2<input id="a" inputmode="decimal" required></label><button class="quiet" id="pause" type="button">Pausar relógio</button>',button:'Prever tempestade',hint:'Tₓ = 3, Tᵧ = 2, x′(t) = 2t e y′(t) = 3. Multiplique os pares e some.'},
 {name:'O tesouro escondido',eyebrow:'INVESTIGUE O RELEVO',title:'Nem todo ponto<br>crítico é um topo.',sprite:'assets/treasure-chest.svg',map:'SUPERFÍCIE • f(x, y) = x³ − 3xy + y³',body:'Considere f(x, y) = x³ − 3xy + y³. O mapa prometia um baú no ponto mais alto. Investigue: encontre os dois pontos críticos (em qualquer ordem) e classifique cada um.',formula:'fₓ = 3x² − 3y = 0<br>fᵧ = −3x + 3y² = 0',fields:'<label>x₁<input id="a" inputmode="decimal" required></label><label>y₁<input id="b" inputmode="decimal" required></label><label class="wide">Tipo do primeiro ponto<select id="type1" required><option value="">Escolha…</option><option value="min">Mínimo local</option><option value="max">Máximo local</option><option value="saddle">Ponto de sela</option></select></label><label>x₂<input id="c" inputmode="decimal" required></label><label>y₂<input id="d" inputmode="decimal" required></label><label class="wide">Tipo do segundo ponto<select id="type2" required><option value="">Escolha…</option><option value="min">Mínimo local</option><option value="max">Máximo local</option><option value="saddle">Ponto de sela</option></select></label>',button:'Localizar o tesouro',hint:'Use y = x² e x = y². Depois use D = fₓₓfᵧᵧ − (fₓᵧ)² = 36xy − 9. D < 0 indica sela; D > 0 e fₓₓ > 0 indicam mínimo.'},
 {name:'Fuga da ilha',eyebrow:'OTIMIZE A CARGA',title:'A melhor escolha.<br>A grande fuga.',sprite:'assets/bus.svg',map:'RESTRIÇÃO • x² + y² = 25',body:'Maximize f(x, y) = xy sujeito a x² + y² = 25. Informe o valor máximo e um par que o atinge. Para recursos não negativos, use o par positivo; o par negativo também resolve o problema matemático.',formula:'∇f = λ∇g<br>y = 2λx &nbsp; · &nbsp; x = 2λy',fields:'<label class="wide">Valor máximo de xy<input id="a" inputmode="decimal" required></label><label>x ótimo<input id="b" inputmode="decimal" required></label><label>y ótimo<input id="c" inputmode="decimal" required></label><p>Use decimais, por exemplo com 3 casas. Vírgula ou ponto são aceitos.</p>',button:'Preparar a fuga',hint:'Some (x − y)² ≥ 0 com a restrição para concluir 2xy ≤ 25. A igualdade acontece quando x = y.'}
];
function num(id){const raw=$(id).value.trim().replace(',','.');return raw!==''&&/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw)?Number(raw):NaN}
const near=(a,b,t=.01)=>Number.isFinite(a)&&Math.abs(a-b)<t;
function render(){clearInterval(timer);solved=false;attempts=0;remaining=120;paused=false;const s=stages[phase];$('mission').textContent=`0${phase+1} / 05`;$('score').textContent=score+' XP';$('steps').innerHTML=stages.map((_,i)=>`<span class="${i<phase?'done':i===phase?'active':''}" aria-label="Missão ${i+1}${i<phase?' concluída':i===phase?' atual':' bloqueada'}"></span>`).join('');$('eyebrow').textContent=s.eyebrow;$('worldTitle').innerHTML=s.title;$('sprite').src=s.sprite;$('sprite').className='';$('storm').style.opacity=phase===2?'.6':'0';$('mapLabel').textContent=s.map;$('panel').innerHTML=`<div class="kicker">MISSÃO 0${phase+1} / 05</div><h2>${s.name}</h2><p>${s.body}</p><div class="formula">${s.formula}</div><form id="answer"><div class="fields">${s.fields}</div><button class="submit" type="submit">${s.button}</button></form>`;$('feedback').textContent='';$('solution').hidden=true;$('next').hidden=true;$('hint').hidden=false;$('clock').textContent='';$('answer').addEventListener('submit',check);if(phase===0){['x','y'].forEach(id=>$(id).addEventListener('input',()=>{px=num('x');py=num('y');draw()}))}if(phase===2){$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Retomar relógio':'Pausar relógio';updateClock()};timer=setInterval(()=>{if(!paused&&!solved){remaining=Math.max(0,remaining-1);updateClock();if(!remaining){clearInterval(timer);$('feedback').className='';$('feedback').textContent='A tempestade chegou! Continue resolvendo sem penalidade.';$('pause').disabled=true}}},1000);updateClock()}draw()}
function updateClock(){$('clock').textContent=(paused?'PAUSADO • ':'')+`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;$('storm').style.boxShadow=`inset 0 0 ${90+(120-remaining)}px ${40+(120-remaining)/2}px #852ade`}
function check(e){e.preventDefault();if(solved)return;attempts++;let ok=false,explain='';const a=num('a');if(phase===0){px=num('x');py=num('y');ok=Number.isInteger(px)&&Number.isInteger(py)&&Math.abs(px)<=5&&Math.abs(py)<=5&&near(a,px*px+py*py);explain=`h(${px}, ${py}) = ${px}² + ${py}² = ${px*px+py*py}. Você pousou com segurança!`}
if(phase===1){ok=near(a,2)&&near(num('b'),8)&&near(num('c'),-9);explain='f(1,2) = 9, fₓ(1,2) = 2 e fᵧ(1,2) = 8. Logo, z = 9 + 2(x − 1) + 8(y − 2) = 2x + 8y − 9. O plano aproxima o terreno perto do ponto; não nivela toda a superfície.'}
if(phase===2){ok=near(a,18);explain='dT/dt = 3(2t) + 2(3) = 6t + 6. Em t = 2, a taxa é 18. Conferência: T(t) = 3t² + 6t.'}
if(phase===3){const b=num('b'),c=num('c'),d=num('d');const t1=$('type1').value,t2=$('type2').value;const point=(x,y,t)=>near(x,0,1e-6)&&near(y,0,1e-6)&&t==='saddle'||near(x,1,1e-6)&&near(y,1,1e-6)&&t==='min';ok=point(a,b,t1)&&point(c,d,t2)&&!near(a,c,1e-6);explain='y = x² e x = y² levam a x⁴ = x: as soluções reais são 0 e 1. Em (0,0), D = −9: sela. Em (1,1), D = 27 e fₓₓ = 6: mínimo local, com f = −1. Não existe máximo global: f(t,0) = t³ cresce sem limite. O tesouro era descobrir o erro do mapa!'}
if(phase===4){const b=num('b'),c=num('c');ok=near(a,12.5)&&near(Math.abs(b),5/Math.sqrt(2))&&near(b,c)&&near(b*b+c*c,25,.1);explain='Como (x − y)² ≥ 0, temos xy ≤ (x² + y²)/2 = 25/2. O máximo global é 12,5, atingido em (5/√2, 5/√2) e (−5/√2, −5/√2). Cada coordenada tem módulo aproximado de 3,535534. Para a carga, escolha o par positivo.'}
$('feedback').className=ok?'success':'error';if(!ok){$('feedback').textContent='Ainda não. Confira os valores e tente novamente — a pista pode ajudar.';return}solved=true;clearInterval(timer);score+=Math.max(40,120-20*(attempts-1));$('score').textContent=score+' XP';$('feedback').textContent='✓ Missão concluída!';$('solution').innerHTML='<strong>Entenda a solução</strong><p>'+explain+'</p>';$('solution').hidden=false;$('next').hidden=false;$('next').textContent=phase===4?'Escapar da ilha →':'Próxima missão →';$('hint').hidden=true;$('answer').querySelectorAll('input,select,button').forEach(el=>el.disabled=true);$('sprite').className='celebrate';draw()}
$('hint').onclick=()=>{$('feedback').className='';$('feedback').textContent=stages[phase].hint};$('next').onclick=()=>{if(phase<4){phase++;render();focusMission()}else{clearInterval(timer);$('panel').innerHTML=`<div class="kicker">EXPEDIÇÃO CONCLUÍDA</div><h2>★ Vitória na ilha!</h2><p>Você completou as cinco missões de cálculo multivariável.</p><div class="formula">${score} XP conquistados</div><p>Funções • planos tangentes • regra da cadeia • pontos críticos • multiplicadores de Lagrange</p><button id="again">Jogar novamente</button>`;$('again').onclick=reset;$('feedback').textContent='';$('solution').hidden=true;$('next').hidden=true;$('worldTitle').innerHTML='Cálculo dominado.<br>Fuga concluída.';$('eyebrow').textContent='VITÓRIA NA ILHA';$('sprite').src='assets/bus.svg';$('steps').querySelectorAll('span').forEach(el=>el.className='done')}};function reset(){phase=0;score=0;px=3;py=5;render();focusMission()}$('restart').onclick=()=>{if(score===0||confirm('Recomeçar a expedição e zerar a pontuação?'))reset()};
// Gráfico isométrico real das funções: cada quadrilátero é uma amostra da superfície.
function draw(){const canvas=$('terrain'),r=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=r.width*dpr;canvas.height=r.height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=r.width,h=r.height,scale=w/24;const zfn=(x,y)=>phase===0?x*x+y*y:phase===1?x*x+2*y*y:phase===2?3*x+2*y:phase===3?x*x*x-3*x*y+y*y*y:0;const factor=phase===3?.24:phase===1?.45:.65;const proj=(x,y,z)=>[w/2+(x-y)*scale,h*.74+(x+y)*scale*.40-z*factor];function polygon(points,color,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
for(let x=-5;x<5;x+=.5)for(let y=-5;y<5;y+=.5){const z=zfn(x,y);polygon([[x,y],[x+.5,y],[x+.5,y+.5],[x,y+.5]].map(([a,b])=>proj(a,b,zfn(a,b))),`hsl(${phase===2?265:142-z*.35} 58% ${37+((x+y+10)/20)*18}%)`,'#123b3d33')}
if(phase===1&&solved)polygon([[-1,0],[3,0],[3,4],[-1,4]].map(([x,y])=>proj(x,y,2*x+8*y-9)),'#ffbf4488','#ffe07d');ctx.strokeStyle='#e8faffaa';ctx.lineWidth=1;[[[-5,0],[5,0]],[[0,-5],[0,5]]].forEach(line=>{ctx.beginPath();line.forEach(([x,y],i)=>i?ctx.lineTo(...proj(x,y,zfn(x,y))):ctx.moveTo(...proj(x,y,zfn(x,y))));ctx.stroke()});ctx.fillStyle='white';ctx.font='bold 14px system-ui';ctx.fillText('x',...proj(5.3,0,zfn(5,0)));ctx.fillText('y',...proj(0,5.3,zfn(0,5)));if(phase===4){ctx.strokeStyle='#ffdf64';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<=100;i++){const angle=i/100*Math.PI*2,p=proj(5*Math.cos(angle),5*Math.sin(angle),0);i?ctx.lineTo(...p):ctx.moveTo(...p)}ctx.stroke()}
if(phase===0&&Number.isFinite(px)&&Number.isFinite(py)&&Math.abs(px)<=5&&Math.abs(py)<=5){const p=proj(px,py,zfn(px,py));ctx.fillStyle='#ff6b35';ctx.beginPath();ctx.arc(...p,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(`(${px}, ${py})`,p[0]+12,p[1]-5)}
}
window.addEventListener('resize',draw);render();

function focusMission(){const heading=$('panel').querySelector('h2');heading.tabIndex=-1;heading.focus({preventScroll:true});if(window.innerWidth<=950)$('panel').scrollIntoView({block:'start',behavior:'instant'});}
