'use strict';
const $=id=>document.getElementById(id);
const classes={
 construtor:{name:'Construtor',icon:'wall',bonus:'Constrói a plataforma do plano tangente com velocidade 50% maior: 1,2 s em vez de 1,8 s.'},
 explorador:{name:'Explorador',icon:'compass',bonus:'Revela no mapa o gradiente da função de cada região já desbloqueada.'},
 estrategista:{name:'Estrategista',icon:'target',bonus:'Na missão de Lagrange, o primeiro erro não retira vida: uma tentativa protegida extra.'},
 guerreiro:{name:'Guerreiro',icon:'sword',bonus:'Na missão de máximos e mínimos, causa 125 de dano em vez de 100 e recebe 25 XP extras.'}
};
const headNames={capacete:'Capacete de Matemático',bandana:'Bandana',coroa:'Coroa Real'};
const bodyNames={armadura:'Armadura de Aço',tatico:'Traje Tático',manto:'Manto Arcano'};
const fields=(labels,expected)=>labels.map((label,i)=>`<label>${label}<input id="answer-${i}" type="text" inputmode="${expected?.[i]<0?'text':'decimal'}" autocomplete="off" required></label>`).join('');
const missions=[
 {title:'Funções de várias variáveis',region:'Praia das Coordenadas',story:'Você caiu na ilha. O Professor Multivariável entrega um altímetro: calcule a altura do pouso antes de explorar.',task:'h(x, y) = x² + y²<br>Calcule h(3, 5).',labels:['Altitude'],values:[34],hint:'Substitua x por 3 e y por 5. Eleve os dois números ao quadrado antes de somar.',solution:'h(3,5) = 3² + 5² = 9 + 25 = 34.',gradient:'∇h(3,5) = (6,10).',item:'Altímetro das Coordenadas'},
 {title:'Derivadas parciais',region:'Bosque das Variáveis',story:'Duas trilhas mudam a energia de sua armadura. Descubra o efeito de cada variável, mantendo a outra constante.',task:'f(x, y) = x²y + 3y²<br>Encontre fₓ(2,1) e fᵧ(2,1).',labels:['fₓ(2,1)','fᵧ(2,1)'],values:[4,10],hint:'Para fₓ, trate y como constante. Para fᵧ, trate x como constante. Só depois substitua o ponto.',solution:'fₓ = 2xy e fᵧ = x² + 6y. Em (2,1), fₓ = 4 e fᵧ = 10.',gradient:'∇f(2,1) = (4,10).',item:'Lente das Parciais'},
 {title:'O caminho do gradiente',region:'Serra do Crescimento',story:'A subida está escondida pela neblina. O gradiente aponta a direção de maior crescimento local da altitude.',task:'h(x,y) = 10 − x² − y²<br>Calcule ∇h(1,2) = (A, B).',labels:['Componente A','Componente B'],values:[-2,-4],hint:'O gradiente reúne as duas derivadas parciais: ∇h = (hₓ,hᵧ).',solution:'∇h = (−2x,−2y). Em (1,2), o vetor é (−2,−4). Ele aponta a direção de maior crescimento; o vetor unitário correspondente é (−1/√5,−2/√5).',gradient:'∇h(1,2) = (−2,−4).',item:'Bússola do Gradiente'},
 {title:'Construindo um plano tangente',region:'Fortaleza Tangente',story:'É hora de erguer sua base. Uma plataforma tangente aproxima o terreno perto de um ponto.',task:'f(x,y) = x² + 2y², no ponto (1,2).<br>Escreva z = Ax + By + C.',labels:['A','B','C'],values:[2,8,-9],hint:'Use z = f(a,b) + fₓ(a,b)(x−a) + fᵧ(a,b)(y−b). Aqui fₓ = 2x e fᵧ = 4y.',solution:'f(1,2)=9, fₓ(1,2)=2 e fᵧ(1,2)=8. Assim z=9+2(x−1)+8(y−2)=2x+8y−9. Essa aproximação é local.',gradient:'∇f(1,2) = (2,8).',item:'Plataforma Tangente'},
 {title:'A tempestade e a regra da cadeia',region:'Vale da Tempestade',story:'O clima muda enquanto você se desloca. Combine a variação do campo com sua trajetória para prever a taxa de mudança.',task:'T(x,y)=3x+2y; x(t)=t²; y(t)=3t.<br>Calcule dT/dt em t=2.',labels:['Taxa dT/dt'],values:[18],hint:'Use dT/dt = Tₓx′(t) + Tᵧy′(t). As derivadas da trajetória são 2t e 3.',solution:'dT/dt = 3(2t)+2(3)=6t+6. Em t=2, o resultado é 18. Também é possível derivar T(t)=3t²+6t.',gradient:'∇T = (3,2), em qualquer ponto.',item:'Radar da Cadeia'},
 {title:'Derivada direcional',region:'Ponte dos Ventos',story:'O vento define a direção da travessia. Descubra a variação da função nessa direção específica.',task:'f(x,y)=x²+y², no ponto (1,2).<br>u=(3/5,4/5), com ‖u‖=1.<br>Calcule Dᵤf(1,2).',labels:['Derivada direcional'],values:[4.4],hint:'Faça o produto escalar ∇f(1,2) · u. O vetor u já é unitário.',solution:'∇f(1,2)=(2,4). Então Dᵤf=2·3/5+4·4/5=22/5=4,4. O resultado é a taxa na direção indicada.',gradient:'∇f(1,2) = (2,4).',item:'Botas Direcionais'},
 {title:'Duelo dos máximos e mínimos',region:'Cume dos Extremos',story:'O Confusionário protege o ponto mais alto. Encontre o máximo global da altitude e rompa a barreira com sua resposta.',task:'f(x,y)=−x²−y²+4x+6y.<br>Informe o ponto de máximo (x,y) e a altura máxima.',labels:['x do máximo','y do máximo','Altura máxima'],values:[2,3,13],hint:'Resolva fₓ=−2x+4=0 e fᵧ=−2y+6=0. Substitua o ponto. Complete quadrados para provar que é um máximo global.',solution:'O ponto crítico é (2,3), com f(2,3)=13. Como f=13−(x−2)²−(y−3)², esse é o máximo global. A Hessiana é diagonal com entradas −2,−2, portanto negativa definida.',gradient:'∇f(2,3) = (0,0).',item:'Coroa dos Extremos'},
 {title:'A fuga de Lagrange',region:'Portal da Restrição',story:'O portal aceita apenas uma carga equilibrada. Otimize os recursos e conclua sua jornada.',task:'Maximize f(x,y)=xy sob x²+y²=25.<br>Informe o máximo e um par (x,y) que o atinge.',labels:['Valor máximo','x ótimo','y ótimo'],values:null,hint:'Use ∇f=λ∇g: y=2λx e x=2λy. No máximo, x=y. Substitua na restrição. Use decimais com pelo menos 3 casas para x e y.',solution:'xy ≤ (x²+y²)/2=25/2=12,5, com igualdade quando x=y. Os pares são (5/√2,5/√2) e (−5/√2,−5/√2), com módulo ≈3,535534. Para recursos não negativos, use o par positivo. Não se trata de uma restrição linear de peso.',gradient:'∇f=(y,x); ∇g=(2x,2y). No ótimo, ∇f=½∇g.',item:'Chave de Lagrange'}
];
let hero=null,phase=0,hp=100,xp=0,potions=2,completed=[],solved=false,down=false,protectedUsed=false,building=false,buildTimer=null;
function setScreen(id){for(const el of document.querySelectorAll('.screen')){el.hidden=el.id!==id;el.classList.toggle('active',el.id===id)}}
function preview(){$('creation-error').textContent='';const c=classes[$('hero-class').value];$('class-bonus').textContent=c.bonus;$('preview-class').textContent=c.name;$('preview-name').textContent=$('hero-name').value.trim()||'Seu herói';$('class-icon').src=`assets/${c.icon}.svg`;$('preview-head').textContent=headNames[$('head-option').value];$('preview-body').textContent=bodyNames[$('body-option').value];document.querySelector('.hero-preview').className=`hero-preview panel head-${$('head-option').value} body-${$('body-option').value}`;const sum=['int','agi','wis'].reduce((n,key)=>n+Number($('attr-'+key).value),0);$('points-left').textContent=`${sum} / 10 pontos distribuídos`;$('points-left').className=sum===10?'success':'error'}
function startGame(event){event?.preventDefault();const name=$('hero-name').value.trim();const attrs=Object.fromEntries(['int','agi','wis'].map(k=>[k,Number($('attr-'+k).value)]));if(!name||name.length>40){$('creation-error').textContent='Digite um nome de até 40 caracteres.';return}if(Object.values(attrs).some(v=>!Number.isInteger(v)||v<1||v>10)||Object.values(attrs).reduce((a,b)=>a+b,0)!==10){$('creation-error').textContent='Distribua exatamente 10 pontos inteiros, com pelo menos 1 em cada atributo.';return}hero={name,cls:$('hero-class').value,attrs,head:$('head-option').value,body:$('body-option').value};phase=0;hp=100;xp=0;potions=2;completed=[];protectedUsed=false;solved=false;down=false;clearTimeout(buildTimer);building=false;$('creation-error').textContent='';setScreen('game-screen');renderMission();focusPhase()}
function hud(){$('player-display').textContent=hero.name;$('class-display').textContent=classes[hero.cls].name;$('player-icon').src=`assets/${classes[hero.cls].icon}.svg`;$('phase-display').textContent=`FASE ${phase+1} / 8`;$('hp-display').textContent=`${hp} / 100`;$('hp-bar').value=hp;$('xp-display').textContent=xp}
function renderMission(){const m=missions[phase];hud();$('region').textContent=m.region;$('phase-title').textContent=`${phase+1}. ${m.title}`;$('phase-narrative').textContent=m.story;$('mission-number').textContent=String(phase+1).padStart(2,'0');$('mission-text').innerHTML=m.task;$('mission-input').innerHTML=fields(m.labels,m.values);$('action-button').disabled=false;$('action-button').textContent='Confirmar resposta';$('feedback').textContent='';$('solution').hidden=true;$('next-button').hidden=true;$('building').hidden=true;$('hint-button').disabled=false;$('ally-dialogue').textContent='Leia a missão com calma. Se precisar, minha pista ajuda a encontrar o caminho.';$('enemy-dialogue').textContent=phase===6?'Minha barreira tem 100 pontos. Só um máximo bem justificado vai derrubá-la!':'Será que você consegue avançar? Eu aposto na sua pressa…';$('enemy-stats').hidden=phase!==6;$('enemy-hp').textContent='100';$('enemy-bar').value=100}
function parseAnswer(i){const raw=$('answer-'+i).value.trim().replace(',','.');return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw)?Number(raw):NaN}
const near=(x,y,t=.005)=>Number.isFinite(x)&&Math.abs(x-y)<=t;
function correct(values){if(phase!==7)return values.every((v,i)=>near(v,missions[phase].values[i]));const [v,x,y]=values;return near(v,12.5)&&near(Math.abs(x),5/Math.sqrt(2))&&near(x,y)&&near(x*x+y*y,25,.08)}
function checkAnswer(event){event?.preventDefault();if(!hero||solved||building)return;if(down){revive();return}const m=missions[phase],values=m.labels.map((_,i)=>parseAnswer(i));if(values.some(v=>!Number.isFinite(v))){$('feedback').className='error';$('feedback').textContent='Preencha todos os campos com números. Vírgula ou ponto são aceitos; use decimais para frações.';return}if(!correct(values)){let damage=Math.max(5,20-hero.attrs.wis);if(phase===7&&hero.cls==='estrategista'&&!protectedUsed){damage=0;protectedUsed=true}hp=Math.max(0,hp-damage);hud();$('feedback').className='error';$('feedback').textContent=damage?`Ainda não. Você perdeu ${damage} PV. Confira a pista e tente novamente.`:'Tentativa protegida do Estrategista usada: nenhum PV perdido. Recalcule e tente novamente.';$('enemy-dialogue').textContent='A confusão venceu esta rodada. Mas você pode revisar sua estratégia.';if(hp===0){down=true;$('feedback').textContent='Você ficou sem vida. Recupere 60 PV para repetir esta região ou use uma poção no inventário. As regiões concluídas continuam conquistadas.';$('action-button').textContent='Recuperar e tentar de novo';$('mission-input').querySelectorAll('input').forEach(el=>el.disabled=true)}return}
solved=true;completed.push(phase);const warrior=phase===6&&hero.cls==='guerreiro',gain=100+5*hero.attrs.int+(warrior?25:0);xp+=gain;hp=Math.min(100,hp+hero.attrs.agi*2);if(completed.length===3||completed.length===6)potions++;hud();$('feedback').className='success';$('feedback').textContent=`Região conquistada! +${gain} XP. Recuperação de até ${hero.attrs.agi*2} PV.${warrior?' Golpe do Guerreiro: 125 de dano!':''}`;$('solution').innerHTML='<strong>Entenda a solução</strong><p>'+m.solution+'</p>';$('solution').hidden=false;$('ally-dialogue').textContent='Muito bem! Leia a solução e guarde o novo item no inventário.';$('enemy-dialogue').textContent='Você desfez minha confusão… por enquanto.';$('action-button').disabled=true;$('hint-button').disabled=true;$('mission-input').querySelectorAll('input').forEach(el=>el.disabled=true);if(phase===6){$('enemy-hp').textContent='0';$('enemy-bar').value=0}$('next-button').textContent=phase===7?'Atravessar o portal →':'Próxima região →';if(phase===3){building=true;$('building').hidden=false;const duration=hero.cls==='construtor'?1200:1800;$('build-fill').style.transition='none';$('build-fill').style.width='0';void $('build-fill').offsetWidth;$('build-fill').style.transition=`width ${duration}ms linear`;$('build-fill').style.width='100%';buildTimer=setTimeout(()=>{building=false;$('building').hidden=true;$('next-button').hidden=false},duration)}else $('next-button').hidden=false}
function revive(){hp=60;down=false;renderMission();$('feedback').textContent='Você recuperou 60 PV. Releia a missão e tente novamente.'}
function nextMission(){if(!solved||building)return;if(phase===7){setScreen('victory-screen');$('victory-name').textContent=`${hero.name}, você escapou da ilha!`;$('victory-stats').textContent=`${xp} XP • ${completed.length} relíquias • ${hp} PV`;$('victory-screen').scrollIntoView({block:'start'});return}phase++;solved=false;down=false;renderMission();focusPhase()}
function focusPhase(){$('phase-title').focus({preventScroll:true});$('phase-container').scrollIntoView({block:'start',behavior:'instant'})}
function showMap(){if(!hero)return;$('map-grid').innerHTML=missions.map((m,i)=>`<button class="map-node ${completed.includes(i)?'done':i===phase?'current':''}" data-region="${i}" ${i>phase?'disabled':''}>${i+1}. ${m.region}<span>${completed.includes(i)?'Conquistada':i===phase?'Você está aqui':'Bloqueada'}</span></button>`).join('');$('map-grid').querySelectorAll('button').forEach(b=>b.onclick=()=>mapDetail(Number(b.dataset.region)));mapDetail(phase);$('map-screen').showModal()}
function mapDetail(i){const m=missions[i];$('map-detail').innerHTML=`<h3>${m.title}</h3><p>${m.task}</p>${hero.cls==='explorador'?`<p class="success"><strong>Visão do Explorador:</strong> ${m.gradient}</p>`:''}${completed.includes(i)?`<p>${m.solution}</p>`:'<p>Conquiste esta região para liberar a solução.</p>'}`}
function inventory(){const gear=document.createElement('p');gear.textContent=`${hero.name} • ${headNames[hero.head]} • ${bodyNames[hero.body]}`;$('inventory-items').replaceChildren(gear);const wrap=document.createElement('div');wrap.innerHTML=`<div class="item"><strong>Poções de recuperação: ${potions}</strong><p>Cada poção recupera até 35 PV. Você recebe uma poção extra ao concluir as regiões 3 e 6.</p><button id="use-potion" ${potions===0||hp===100||completed.length===8?'disabled':''}>Usar poção (+35 PV)</button><p id="potion-status" role="status"></p></div><div class="item"><strong>Seus atributos</strong><p>INT ${hero.attrs.int} · AGI ${hero.attrs.agi} · WIS ${hero.attrs.wis}</p></div><h3>Relíquias conquistadas (${completed.length}/8)</h3>${completed.length?completed.map(i=>`<div class="item">${missions[i].item}</div>`).join(''):'<p>Conclua a primeira missão para ganhar seu primeiro item.</p>'}`;$('inventory-items').append(wrap);$('use-potion').onclick=()=>{if(potions===0||hp===100||completed.length===8)return;potions--;const healed=Math.min(35,100-hp);hp+=healed;if(down){down=false;renderMission()}hud();inventory();$('potion-status').textContent=`Poção usada: +${healed} PV. Vida atual: ${hp}.`;$('use-potion').focus()}}
function showInventory(){if(!hero)return;inventory();$('inventory-screen').showModal()}
function showHelp(){if(!hero)return;$('help-text').innerHTML=`<p><strong>Seu benefício de classe:</strong> ${classes[hero.cls].bonus}</p><ul><li>INT: cada ponto adiciona 5 XP à recompensa de cada região.</li><li>AGI: cada ponto recupera 2 PV após uma resposta correta, até 100 PV.</li><li>WIS: reduz o dano de um erro. Você perde no máximo 20 − WIS PV, com mínimo de 5.</li><li>Um acerto concede 100 XP de base e uma relíquia. Não há bônus por responder rápido.</li><li>Se a vida chegar a zero, você pode recuperar 60 PV e repetir a região. Pedir pistas não custa vida nem XP.</li><li>Digite números decimais com ponto ou vírgula. Não digite expressões ou frações com barra.</li><li>Cabeça e corpo mudam apenas a aparência e a ficha do herói.</li><li>O progresso não é salvo ao fechar ou recarregar a página.</li></ul>`;$('help-screen').showModal()}
function closeModal(id){$(id).close()}
function newJourney(){clearTimeout(buildTimer);building=false;hero=null;document.querySelectorAll('dialog[open]').forEach(d=>d.close());setScreen('character-creation');$('hero-name').focus();window.scrollTo(0,0)}
$('character-form').addEventListener('submit',startGame);$('character-form').addEventListener('input',preview);$('character-form').addEventListener('change',preview);$('answer-form').addEventListener('submit',checkAnswer);$('next-button').onclick=nextMission;$('hint-button').onclick=()=>{$('ally-dialogue').textContent=missions[phase].hint};$('map-button').onclick=showMap;$('inventory-button').onclick=showInventory;$('help-button').onclick=showHelp;$('new-button').onclick=()=>$('restart-screen').showModal();$('victory-new').onclick=()=>$('restart-screen').showModal();$('confirm-restart').onclick=newJourney;$('victory-map').onclick=showMap;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());preview();
