export type Archetype = 'archer'|'mage'|'dancer'|'orb'|'rogue'|'guardian'|'golem'|'engineer'|'priest'|'titan'|'relic'|'angel';
export type AbilityKind = 'strike'|'double'|'shield'|'heal'|'slow'|'burn'|'haste'|'chain'|'reflect'|'pierce';
export type CardProfile={archetype:Archetype;color:string;glow:string;hair:string;ability:string;kind:AbilityKind;factor:number;amount:number;duration:number;motif:'arrow'|'wave'|'rings'|'shards'|'beam'|'helix';symbol:string};
function p(archetype:Archetype,color:string,glow:string,ability:string,kind:AbilityKind,factor:number,amount:number,motif:CardProfile['motif'],symbol:string,hair='#33221b',duration=3):CardProfile{return {archetype,color,glow,hair,ability,kind,factor,amount,motif,symbol,duration};}
// Paletas, silhuetas e acessórios observados nas ilustrações das cartas.
export const CARD_PROFILES:Record<string,CardProfile>={
 slope:p('archer','#9c2f30','#ffb458','Flecha tangente','pierce',.8,0,'arrow','f′'),
 limit:p('guardian','#294975','#63dfff','Barreira de aproximação','shield',.45,12,'rings','lim'),
 power:p('mage','#8d2028','#ffb23e','Impacto da potência','strike',1.1,0,'helix','xⁿ','#ddd8c6'),
 sine:p('dancer','#087c72','#55ffcd','Onda senoidal','slow',.45,.45,'wave','sin'),
 euler:p('orb','#bc8c28','#ffe17d','Expansão de Euler','burn',.55,3,'rings','eˣ'),
 chain:p('mage','#4c2682','#cf83ff','Composição em cadeia','chain',.6,2,'helix','∘'),
 ln:p('rogue','#16515b','#58e4f4','Precisão logarítmica','pierce',.75,0,'arrow','ln'),
 implicit:p('golem','#4c5267','#a08eff','Escudo implícito','shield',.5,14,'shards','∂'),
 rate:p('engineer','#876039','#63defb','Pulso das taxas','haste',.5,.5,'arrow','dt'),
 cauchy:p('guardian','#223d85','#6abfff','Equilíbrio de Cauchy','shield',.5,10,'rings','≈'),
 taylor:p('mage','#97663a','#ffe08d','Eco de Taylor','double',.4,0,'helix','Σ'),
 newton:p('titan','#1a3964','#ffca68','Salto à raiz','strike',1.05,0,'shards','N'),
 opt:p('relic','#bd902d','#ffe58c','Vetor ótimo','pierce',.85,0,'arrow','⌖'),
 area:p('priest','#176146','#75eed2','Soma restauradora','heal',.4,9,'wave','∫'),
 ftc:p('titan','#b18b39','#88dfff','Raio fundamental','pierce',.9,0,'beam','F'),
 cavalieri:p('mage','#b68a2e','#ffdf85','Seções protetoras','shield',.45,13,'rings','▥','#dad4c5'),
 fractal:p('relic','#157653','#6dffc2','Ramificação fractal','chain',.45,3,'shards','✣'),
 sub:p('mage','#196168','#ffcd68','Transmutação de u','burn',.5,3,'helix','u'),
 parts:p('rogue','#912832','#71e9ff','Duas partes','double',.45,0,'arrow','uv'),
 trap:p('engineer','#88643c','#ffdf72','Malha trapezoidal','shield',.5,8,'beam','▱','#72401f'),
 improper:p('guardian','#34254e','#c679ff','Convergência infinita','shield',.55,15,'rings','∞'),
 continuity:p('priest','#53407d','#c3b5ff','Fluxo contínuo','heal',.4,7,'wave','≈'),
 quotient:p('rogue','#185735','#68f4b4','Corte do quociente','double',.45,0,'arrow','÷'),
 secant:p('guardian','#275640','#e7ff8a','Lâmina secante','pierce',.75,0,'beam','sec'),
 bernoulli:p('mage','#244772','#ffda6d','Explosão de Bernoulli','burn',.6,4,'helix','e','#e2ddd2'),
 inverse:p('mage','#492766','#e0a0ff','Retorno inverso','reflect',.5,.35,'rings','f⁻¹'),
 expchain:p('relic','#775298','#e3a6ff','Elo exponencial','chain',.55,2,'helix','aˣ'),
 root:p('guardian','#286447','#95ffb5','Ruptura da raiz','pierce',.9,0,'shards','√'),
 mirror:p('relic','#6691b1','#a5edff','Reflexão implícita','reflect',.4,.5,'rings','↔'),
 mean:p('guardian','#283c63','#ffe695','Balança de Cauchy','heal',.4,8,'rings','M'),
 growth:p('rogue','#256352','#7bffc6','Arrancada crescente','haste',.55,.6,'arrow','+','#b74725'),
 taylor2:p('mage','#5a347c','#ead1ff','Previsão quadrática','slow',.55,.4,'helix','T₂'),
 miner:p('engineer','#664833','#6ff9c2','Impacto no máximo','strike',1.15,0,'shards','min','#ae4f27'),
 average:p('priest','#1c6669','#ffe09c','Média restauradora','heal',.35,10,'rings','μ'),
 volume:p('priest','#245b9a','#84d9ff','Camadas de volume','shield',.45,12,'rings','V'),
 surface:p('dancer','#244b70','#a1e4ff','Onda de superfície','burn',.5,3,'wave','S'),
 gabriel:p('angel','#f0deac','#ffec98','Sopro de Gabriel','pierce',.9,0,'wave','∞','#d7ac46'),
 'cavalieri-advanced':p('mage','#254a80','#ffde87','Dupla seção','shield',.5,18,'rings','▥²','#ddd5c6'),
 'surface-flux':p('dancer','#206b75','#89e6ff','Fluxo persistente','burn',.45,4,'helix','∯'),
 parts2:p('rogue','#862d30','#8ce9ff','Permuta de golpes','double',.5,0,'arrow','uv'),
 simpson:p('engineer','#8c5b2d','#ffdb84','Três pontos de Simpson','chain',.45,3,'beam','Sₙ','#bc6336'),
 compare:p('mage','#412564','#daa0ff','Comparação defensiva','reflect',.45,.3,'rings','≤'),
 series:p('mage','#30294f','#af8fff','Combo da série','chain',.55,3,'helix','Σ∞'),
 'simpson-advanced':p('mage','#634070','#ffe2a5','Aproximação de Simpson','strike',1.15,0,'beam','Sₙ²','#e1d8c5'),
 comparison:p('guardian','#244778','#9de5ff','Limite comparativo','shield',.5,16,'rings','≤∞'),
};
export function getCardProfile(id:string){return CARD_PROFILES[id]??CARD_PROFILES.slope;}
export function abilityDescription(id:string){const a=getCardProfile(id);const descriptions:Record<AbilityKind,string>={strike:'Impacto concentrado no alvo.',double:'Dois golpes por ativação.',shield:`Gera ${a.amount} de escudo.`,heal:`Cura até ${a.amount} HP do aliado mais ferido.`,slow:`Reduz o movimento em ${Math.round(a.amount*100)}% por ${a.duration}s.`,burn:`Aplica ${a.amount} HP/s por ${a.duration}s.`,haste:`Acelera aliados próximos em ${Math.round(a.amount*100)}% por ${a.duration}s.`,chain:`Atinge até ${a.amount} inimigos próximos.`,reflect:`Reflete ${Math.round(a.amount*100)}% do próximo dano recebido por ${a.duration}s.`,pierce:'Ignora o escudo do alvo.'};return `${a.ability}: ${descriptions[a.kind]}`;}
