"""Build a deterministic bank: existing 38 skills × 5 lists × 5 questions.
Source skill descriptions are pedagogical summaries already used by the site.
Run from any directory. No runtime dependency; JSON is bundled as plain JS.
"""
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[1]
def q(prompt,answer,visual=None,space='lines'):
 d={'prompt':prompt,'answer':answer,'space':space}
 if visual:d['visual']=visual
 return d
def seq(items):return {'type':'sequence','items':list(map(str,items))}
def grid(points=None,size=8):return {'type':'grid','points':points or [],'size':size}
def shapes(items):return {'type':'shapes','items':items}
def solid(name):return {'type':'solid','name':name}
def net(name):return {'type':'net','name':name}
def join(xs):return ', '.join(map(str,xs))
S=['círculo','quadrado','triângulo','retângulo','pentágono']
OBJ=['livro','bola','vaso','mochila','caixa']
COL=['azul','vermelha','verde','amarela','roxa']
# Every branch has five explicit, answerable tasks. n selects a fixed list variant.
def algebra(code,n):
 a=n+2;b=n+4;c=n+6;k=n+2
 if code=='EF01MA09':
  color=COL[n];other=COL[(n+1)%5];x=S[[0,1,2,3,0][n]];y=S[[1,2,3,0,2][n]]
  return [q(f'Os cartões são: A — {x} grande; B — {y} pequeno; C — {x} pequeno; D — {y} grande. Separe-os em dois grupos pela forma.', 'Grupo 1: A e C. Grupo 2: B e D.'),q(f'Agora separe os mesmos cartões A, B, C e D: A — {x} grande; B — {y} pequeno; C — {x} pequeno; D — {y} grande. Use o tamanho como regra.','Grandes: A e D. Pequenos: B e C.'),q(f'Ordene as fitas da menor para a maior: A mede {c} cm; B mede {a} cm; C mede {b} cm.',f'B ({a} cm), C ({b} cm), A ({c} cm).'),q(f'Uma caixa aceita peças de cor {color}. Ana colocou uma peça {color}, outra {other} e outra {color}. Qual precisa sair? Explique.',f'A peça {other}, pois não atende à regra de cor {color}.'),q(f'Desenhe quatro peças: duas grandes e duas pequenas. Separe em grupos e diga qual regra usou. Você consegue agrupá-las de outro jeito?','Resposta aberta: quatro peças, dois tamanhos claramente indicados e critério explicado. Outra classificação pode usar forma ou cor; não exigir cor na impressão.',space='drawing')]
 if code=='EF01MA10':
  x=S[[0,1,2,3,0][n]];y=S[[1,2,3,0,2][n]];start=n+1
  return [q('Complete as duas lacunas seguindo a repetição.',f'{y}; {x}.',seq([x,y,x,'___','___',y])),q(f'A sequência cresce de 1 em 1: {start}, {start+1}, ___, {start+3}, ___. Complete.',f'{start+2} e {start+4}.'),q('Qual figura está faltando? Conte como descobriu.',f'{y}. O grupo que se repete é {x}, {x}, {y}.',seq([x,x,y,x,x,'___'])),q(f'Na fila, repetimos: palma, pé, palma, pé. Qual movimento vem depois de {2*n+4} movimentos?','Palma: a quantidade de movimentos indicada é par; o próximo inicia o par palma–pé.'),q(f'Crie uma sequência de seis desenhos que repita {x} e {y}. Apague um desenho e escreva, embaixo, qual era ele.','Resposta aberta: seis posições alternadas, uma lacuna e sua resposta coerente.',space='drawing')]
 if code=='EF02MA09':
  step=n+2;start=n+3;top=step*8+n
  return [q(f'Comece em {start} e some {step} a cada passo. Escreva seis números contando o inicial.',join(start+step*i for i in range(6))+'.'),q(f'Comece em {top} e subtraia {step} a cada passo. Registre os cinco primeiros números.',join(top-step*i for i in range(5))+'.'),q(f'Os assentos de um corredor começam em {a} e aumentam de 2 em 2. Numere os próximos quatro.',join(a+2*i for i in range(1,5))+'.'),q(f'Escreva uma sequência decrescente de cinco números que comece em {5*k} e termine em {k}, retirando sempre a mesma quantidade.',join(k*i for i in range(5,0,-1))+f'. Retirar {k}.'),q(f'Crie uma sequência de cinco números naturais começando em {b}. Escolha quanto acrescentar, sempre igual, e explique sua regra.',f'Resposta aberta. Exemplo: {join(b+3*i for i in range(5))}; somar 3 a cada passo.')]
 if code=='EF02MA10':
  step=n+2;x=S[[0,1,2,3,0][n]];y=S[[1,2,3,0,2][n]]
  return [q(f'Descreva a regra: {join(a+step*i for i in range(5))}.',f'Somar {step} ao número anterior.'),q('Qual é o menor grupo de figuras que se repete?',f'{x}, {y}, {y}.',seq([x,y,y,x,y,y])),q(f'Compare A: {join(a+step*i for i in range(4))} e B: {join(b+step*i for i in range(4))}. O que as regras têm em comum?',f'As duas somam {step} a cada passo, mas começam em números diferentes.'),q(f'João diz que {join(a+step*i for i in range(4))} aumenta de 1 em 1. Ele tem razão? Mostre a diferença entre dois vizinhos.',f'Não. A diferença é {step}.'),q(f'Desenhe uma sequência repetindo um grupo de três figuras e escreva qual grupo escolheu. Faça duas repetições.','Resposta aberta: um grupo de três elementos, repetido duas vezes sem mudar a ordem.',space='drawing')]
 if code=='EF02MA11':
  x=S[[0,1,2,3,0][n]];y=S[[1,2,3,0,2][n]];s=n+2
  return [q(f'Complete: {a}, {a+s}, ___, {a+3*s}, ___.',f'{a+2*s} e {a+4*s}.'),q(f'Complete: {8*s}, ___, {6*s}, {5*s}, ___.',f'{7*s} e {4*s}.'),q('Descubra as duas figuras que faltam.',f'{x} e {y}.',seq([x,y,y,'___',y,'___',x,y,y])),q(f'Uma fila cresce de {s} em {s}: {s}, {2*s}, {3*s}, ___, {5*s}. Qual número falta e qual foi a regra?',f'{4*s}; somar {s}.'),q(f'Crie uma sequência de seis números aumentando de {s} em {s}. Deixe duas lacunas e escreva o gabarito.',f'Resposta aberta. Exemplo: {s}, ___, {3*s}, {4*s}, ___, {6*s}; respostas {2*s} e {5*s}.')]
 if code=='EF03MA10':
  step=n+3;start=10+n*4
  return [q(f'Descubra a regra e complete os próximos dois termos: {join(start+step*i for i in range(4))}.',f'Somar {step}; {start+4*step}, {start+5*step}.'),q(f'Complete os dois próximos termos e descreva a regra: {join(70+n*5-step*i for i in range(4))}.',f'Subtrair {step}; {70+n*5-4*step}, {70+n*5-5*step}.'),q(f'Uma coleção tem {start} peças e recebe {step} novas por dia. Quantas terá depois de quatro dias? Registre a sequência.',f'{start+4*step}. Sequência: {join(start+step*i for i in range(5))}.'),q(f'A sequência deveria aumentar sempre {step}: {start}, {start+step}, {start+2*step+1}, {start+3*step}. Corrija o termo errado.',f'Trocar {start+2*step+1} por {start+2*step}.'),q(f'Crie uma sequência decrescente de seis termos com passo {step}, sem usar números negativos. Registre a regra.',f'Resposta aberta. Exemplo: {join(step*i for i in range(8,2,-1))}; subtrair {step}.')]
 if code=='EF03MA11':
  total=12+n*3
  return [q(f'Complete para tornar os dois lados iguais: {a} + {total-a} = {b} + ___.',f'{total-b}; ambos os lados valem {total}.'),q(f'Escreva duas adições diferentes que tenham resultado {total}.',f'Resposta aberta. Exemplo: {a}+{total-a} e {b}+{total-b}.'),q(f'Escreva uma subtração com resultado {total} e ligue-a, usando =, a uma adição de mesmo resultado.',f'Exemplo: {total+5} − 5 = {a} + {total-a}. Outras sentenças corretas são válidas.'),q(f'Verifique: {a} + {b} = {a+b+1} − 2. É verdadeiro? Corrija apenas o número 2.',f'Falso; trocar 2 por 1. Ambos os lados passam a valer {a+b}.'),q(f'Complete a igualdade de três expressões: {total+4} − 4 = ___ + {a} = {total+8} − ___.',f'{total-a} e 8; todas valem {total}.')]
 if code=='EF04MA11':
  m=n+3
  return [q(f'Escreva os seis primeiros múltiplos positivos de {m}.',join(m*i for i in range(1,7))+'.'),q(f'Complete os múltiplos de {m}: {m}, ___, {3*m}, ___, {5*m}, ___.',f'{2*m}, {4*m}, {6*m}.'),q(f'Quais pertencem à sequência dos múltiplos de {m}: {join([3*m,3*m+1,5*m,7*m+1,8*m])}? Justifique com multiplicações.',f'{3*m}={m}×3; {5*m}={m}×5; {8*m}={m}×8.'),q(f'As peças são guardadas em caixas de {m}. É possível guardar {8*m} peças sem sobra? E {8*m+1}?',f'Sim: 8 caixas. Para {8*m+1}, sobra 1 peça ao completar 8 caixas.'),q(f'Encontre dois múltiplos positivos comuns a {m} e {2*m}. Explique sua escolha.',f'Exemplo: {2*m} e {4*m}. São múltiplos de ambos; aceitar outros.')]
 if code=='EF04MA12':
  d=n+3;r=n+1
  return [q(f'Divida {3*d+r}, {5*d+r} e {7*d+r} por {d}. Registre quociente e resto em cada caso.',f'Quocientes 3, 5 e 7; resto {r} nos três casos.'),q(f'Qual número não pertence ao grupo com resto {r} ao dividir por {d}: {join([2*d+r,4*d+r,6*d+r+1,8*d+r])}?',f'{6*d+r+1}; os outros deixam resto {r}.'),q(f'Escreva três números maiores que {d} que deixem resto 1 ao serem divididos por {d}.',f'Exemplo: {d+1}, {2*d+1}, {3*d+1}.'),q(f'Em {3*d+r} peças, ao formar grupos de {d}, sobram {r}. Se acrescentarmos {d} peças, o resto muda? Explique.',f'Não. Forma-se mais um grupo completo; continuam sobrando {r}.'),q(f'Continue o grupo de mesmo resto: {d+r}, {2*d+r}, {3*d+r}, ___, ___. Qual é o divisor considerado e o resto?',f'{4*d+r}, {5*d+r}; divisor {d}, resto {r}.')]
 if code=='EF04MA13':
  x=20+n*6;y=n+7;u=n+3;v=n+5
  return [q(f'Use {x} + {y} = {x+y} para escrever duas subtrações relacionadas.',f'{x+y} − {x} = {y}; {x+y} − {y} = {x}.'),q(f'Use {u} × {v} = {u*v} para escrever duas divisões relacionadas.',f'{u*v} ÷ {u} = {v}; {u*v} ÷ {v} = {u}.'),q(f'Qual número somado a {y} dá {x+y}? Mostre a operação inversa.',f'{x}; {x+y} − {y} = {x}.'),q(f'{u*v} livros foram distribuídos igualmente em {u} caixas. Quantos por caixa? Confira multiplicando.',f'{v} livros; {u} × {v} = {u*v}.'),q(f'Um colega afirma que {u*v} ÷ {u} = {v+1}. Use a multiplicação para verificar e corrigir.',f'{u} × {v+1} = {u*(v+1)}, diferente de {u*v}. O quociente correto é {v}.')]
 if code=='EF04MA14':
  total=18+n*4;inc=n+3
  return [q(f'Parta de {a} + {total-a} = {total}. Some {inc} aos dois membros e escreva a nova igualdade.',f'({a}+{total-a})+{inc} = {total}+{inc}; ambos valem {total+inc}.'),q(f'Em {total+inc} = {total} + {inc}, subtraia {inc} dos dois membros. O que resulta?',f'{total} = {total}.'),q(f'A igualdade {total} = {total} recebeu +{inc} só à esquerda. Ela continua verdadeira? Como corrigir mantendo essa adição?',f'Não; adicionar também {inc} à direita, obtendo {total+inc} = {total+inc}.'),q(f'Uma balança equilibrada tem {total} unidades em cada prato. Retiramos {a} de cada lado. Quanto fica em cada prato? Ela permanece equilibrada?',f'{total-a} em cada prato; sim.'),q(f'Crie uma igualdade entre uma adição e um número. Faça a mesma subtração nos dois membros, sem resultados negativos, e explique por que ela permanece verdadeira.',f'Resposta aberta. Exemplo: {a}+{b}={a+b}; subtrair {a} de cada membro deixa {b}={b}.')]
 if code=='EF04MA15':
  x=5+n*2;y=n+3
  return [q(f'Descubra o número: □ + {y} = {x+y}. Confira substituindo.',f'□ = {x}; {x}+{y}={x+y}.'),q(f'Complete: {x+y} − □ = {y}.',f'□ = {x}.'),q(f'Complete: □ × {y} = {x*y}.',f'□ = {x}.'),q(f'Complete: □ ÷ {y} = {x}.',f'□ = {x*y}.'),q(f'Qual número torna verdadeira a igualdade □ + {y} = {x} + {y+2}? Mostre o valor dos dois membros.',f'□ = {x+2}; ambos valem {x+y+2}.')]
 if code=='EF05MA10':
  v=12+n*6;m=n+2
  return [q(f'Em {v} = {v}, some {m} a ambos os membros. Registre e explique o que permanece.',f'{v+m} = {v+m}; a igualdade permanece.'),q(f'Em {v+m} = {v+m}, subtraia {m} dos dois membros.',f'{v} = {v}.'),q(f'Partindo de {v} = {v}, multiplique os dois membros por {m}. Escreva a igualdade obtida.',f'{v*m} = {v*m}.'),q(f'Partindo de {v*m} = {v*m}, divida os dois membros por {m}. Por que o divisor pode ser usado?',f'{v} = {v}. O divisor é diferente de zero.'),q(f'Parta de {v} = {v}. Um aluno soma {m} à esquerda e multiplica a direita por {m}. A igualdade permanece neste caso? Calcule e explique.',f'Não: {v+m} é diferente de {v*m}. Foram realizadas operações diferentes; não se preservou a igualdade.')]
 if code=='EF05MA11':
  x=15+n*3;y=6+n
  return [q(f'A biblioteca tinha alguns livros e recebeu {y}. Agora tem {x+y}. Escreva uma igualdade com □ e descubra quantos havia.',f'□ + {y} = {x+y}; havia {x} livros.'),q(f'De {x+y} mudas, algumas foram plantadas e restaram {y}. Escreva e resolva uma igualdade para a quantidade plantada.',f'{x+y} − □ = {y}; foram plantadas {x}.'),q(f'{y} pacotes iguais contêm {x*y} figurinhas ao todo. Quantas há em cada pacote? Represente por igualdade.',f'{y} × □ = {x*y}; {x} figurinhas por pacote.'),q(f'Uma quantidade de lápis foi dividida igualmente entre {y} estudantes; cada um recebeu {x}. Qual era a quantidade? Escreva a igualdade.',f'□ ÷ {y} = {x}; quantidade {x*y}.'),q(f'Crie e resolva um problema que corresponda a □ + {y} = {x+y}.','Resposta aberta: situação de quantidade inicial desconhecida e acréscimo conhecido. O resultado deve ser '+str(x)+'. Não aceitar um enunciado que pergunte apenas a soma conhecida.')]
 if code=='EF05MA12':
  price=3+n;portions=2*(n+2);cups=n+3
  return [q(f'Cada caderno custa R$ {price}, sem desconto. Complete o custo para 2, 4 e 6 cadernos.',f'R$ {2*price}, R$ {4*price} e R$ {6*price}.'),q(f'Uma receita para {portions} pessoas usa {cups} copos de leite. Quantos copos para {3*portions} pessoas, mantendo a proporção?',f'{3*cups} copos; triplicar todas as quantidades.'),q(f'Uma equipe produz {4*(n+3)} peças em 2 horas, sempre no mesmo ritmo. Quantas produz em 5 horas?',f'{10*(n+3)} peças; {2*(n+3)} por hora.'),q(f'Uma loja cobra R$ {2*price} por 2 unidades e R$ {4*price+2} por 4. Preço e quantidade são diretamente proporcionais nessas ofertas? Justifique.',f'Não. O dobro de R$ {2*price} seria R$ {4*price}, não R$ {4*price+2}.'),q(f'No desenho, cada 1 cm representa {n+2} m reais. Um caminho mede {b} cm no desenho. Qual é a medida real? Mostre a relação.',f'{b*(n+2)} m; multiplicar {b} por {n+2}.')]
 if code=='EF05MA13':
  unit=6+n*2;total=3*unit
  return [q(f'Divida {total} tampinhas entre Ana e Bia, de modo que Ana receba o dobro de Bia. Quantas para cada uma?',f'Ana: {2*unit}; Bia: {unit}. São 3 partes de {unit}.'),q(f'Duas caixas guardam {4*unit} livros. A maior tem o triplo da menor. Quantos livros há em cada uma?',f'Maior: {3*unit}; menor: {unit}.'),q(f'Na partilha de {total} na razão 2 para 1, um aluno dividiu o total por 2 e deu metade a cada um. O que precisa corrigir?',f'Dividir por 3 unidades de razão, não por 2 pessoas. As partes corretas são {2*unit} e {unit}.'),q(f'Uma coleção tem {5*unit} peças. Para cada 2 peças vermelhas há 3 azuis. Quantas de cada cor?',f'{2*unit} vermelhas e {3*unit} azuis; total de 5 unidades de razão.'),q(f'Crie um problema de partilha de {total} objetos em duas partes, uma com o dobro da outra. Desenhe barras e confira a soma.',f'Resposta aberta com partes {unit} e {2*unit}, cuja soma é {total}; o desenho deve mostrar 1 e 2 unidades iguais.',space='drawing')]
 raise ValueError(code)

def geometry(code,n):
 a=n+2;b=n+3;k=n+2
 names=['biblioteca','horta','quadra','cantina','secretaria']
 place=names[n]
 if code in ['EF01MA11','EF01MA12']:
  labels=[OBJ[(n+i)%5] for i in range(4)]
  room={'type':'room','labels':labels}
  right,left,front,back=labels
  if code=='EF01MA11':
   return [q('Você está no centro, olhando para o topo da folha. Qual objeto está à sua direita?',right.capitalize()+'.',room),q('Você está no centro, olhando para o topo da folha. Qual objeto está à sua esquerda?',left.capitalize()+'.',room),q('Você está no centro, olhando para o topo da folha. Qual objeto está em frente e qual está atrás de você?',f'Em frente: {front}. Atrás: {back}.',room),q(f'Desenhe você olhando para o topo da folha. Coloque um(a) {right} à sua direita e um(a) {left} à sua esquerda.',f'Figura da pessoa no centro; {right} do lado direito da folha e {left} do lado esquerdo.',space='drawing'),q(f'Imagine que você está de costas para o(a) {back} e olhando para o(a) {front}. Se der meia-volta sem sair do lugar, qual ficará em frente e qual ficará atrás?',f'Em frente: {back}; atrás: {front}.',room)]
  return [q(f'Use a pessoa no centro, olhando para o topo da folha, como referência. Onde está o(a) {right}?','À direita da pessoa.',room),q(f'Na mesma organização, use o(a) {left} como referência. A pessoa está do lado esquerdo ou direito desse objeto na folha?','Do lado direito do objeto na folha.',room),q(f'Uma pessoa fica no centro olhando para o topo. Outra fica no mesmo ponto olhando para a parte de baixo da folha. O(a) {right} está à direita das duas? Explique.',f'Não. Está à direita da primeira e à esquerda da segunda. A posição depende da orientação de quem observa.',room),q(f'Desenhe um(a) {front} entre duas cadeiras. Explique sua posição em relação à cadeira da esquerda e depois à cadeira da direita.',f'O objeto fica à direita da cadeira esquerda e à esquerda da cadeira direita, considerando os lados da folha.',space='drawing'),q(f'Alguém diz: “O(a) {back} está atrás”. Que informação falta para localizar sem dúvida? Use a figura para completar a frase.',f'Falta indicar o referencial e a orientação. Exemplo: {back} está atrás da pessoa central que olha para o topo.',room)]
 if code in ['EF01MA13','EF02MA14','EF03MA13']:
  models=['cubo','cilindro','cone','esfera','bloco retangular'];m=models[n]
  obj={'cubo':'um dado de faces quadradas','cilindro':'uma lata de conserva','cone':'um chapéu de festa pontudo','esfera':'uma bola de futebol','bloco retangular':'uma caixa de sapatos'}
  if code=='EF01MA13':
   return [q(f'{obj[m].capitalize()} lembra qual sólido geométrico?',m.capitalize()+'.'),q('Qual objeto lembra uma esfera: bola ou caixa de sapatos?','A bola.'),q(f'Observe o desenho. Escreva o nome do sólido e cite um objeto que o lembre.',f'{m.capitalize()}; exemplo: {obj[m]}.',solid(m)),q(f'Desenhe um objeto da sala ou de casa que lembre um cilindro. Explique a semelhança.',f'Resposta aberta: lata, rolo ou outro objeto aproximadamente cilíndrico; relacionar a forma, não a finalidade.',space='drawing'),q(f'Compare {obj[m]} com um desenho plano de um círculo. Qual pode ser segurado como objeto com volume? Explique.',f'{obj[m].capitalize()} é um objeto tridimensional. O círculo desenhado é uma figura plana; o suporte de papel não se confunde com a figura.')]
  return [q('Nomeie o sólido representado e associe a um objeto familiar.',f'{m.capitalize()}; {obj[m]}.',solid(m)),q(f'Compare {obj[m]} e uma bola. Eles lembram o mesmo sólido?',('Sim, ambos lembram esferas.' if m=='esfera' else f'Não. O primeiro lembra {m}; a bola lembra esfera.')),q('Associe: dado; caixa de sapatos; lata. Use: cubo, bloco retangular, cilindro.','Dado → cubo; caixa de sapatos → bloco retangular; lata → cilindro.'),q(f'Uma embalagem tem uma base quadrada e faces laterais triangulares que se encontram numa ponta. Ela lembra cone ou pirâmide? Explique.', 'Pirâmide de base quadrada. O cone tem base circular e superfície lateral curva.'),q(f'Desenhe dois objetos diferentes que lembrem {m}. Escreva o nome de cada objeto e o sólido associado.',f'Resposta aberta: dois objetos coerentes com {m}. Para cubo, aceitar caixa cúbica e cubo de gelo; não exigir perfeição geométrica.',space='drawing')]
 if code in ['EF01MA14','EF02MA15']:
  orders=[['círculo','quadrado','triângulo','retângulo'],['triângulo','círculo','retângulo','quadrado'],['retângulo','triângulo','quadrado','círculo'],['quadrado','retângulo','círculo','triângulo'],['círculo','triângulo','quadrado','retângulo']]
  arr=orders[n]
  return [q('Dê o nome das figuras A, B, C e D.', '; '.join(f'{chr(65+i)}: {s}' for i,s in enumerate(arr))+'.',shapes(arr)),q('Qual figura desenhada tem três lados? E qual não tem lados retos?',f'Triângulo ({chr(65+arr.index("triângulo"))}); círculo ({chr(65+arr.index("círculo"))}).',shapes(arr)),q('Observe os dois quadrados: um está girado. A mudança de posição muda o nome da figura? Explique.','Não. Os dois continuam quadrados; girar a figura não muda suas características.',{'type':'rotated','shape':'quadrado','size':n+2}),q(f'Desenhe um triângulo pequeno e outro maior, em posições diferentes. O que os dois têm em comum?','Ambos têm três lados e três vértices. Aceitar desenho com tamanhos e orientações distintos.',space='drawing'),q(f'Uma caixa tem uma face em forma de retângulo de {a} cm por {b+2} cm. Desenhe essa face e diga se ela é um triângulo, um círculo ou um retângulo.',f'Retângulo: quatro lados e quatro cantos retos. Não exigir escala exata nos anos iniciais.',space='drawing')]
 if code in ['EF02MA12','EF03MA12']:
  moves=a;vertical=b;start=(1,1);end=(1+moves,1+vertical)
  diagram=grid([['E',1,1],['D',*end]],9)
  return [q(f'Na malha, cada intervalo vale um passo. Da entrada E, ande {moves} passos para a direita e {vertical} para cima. Marque a chegada.',f'Chegada D, na posição ({end[0]}, {end[1]}). No 2º ano, basta marcar, sem exigir escrita de coordenadas.',diagram,space='drawing'),q(f'Para voltar de D até E, faça o caminho da questão anterior ao contrário. Descreva os passos.',f'{vertical} para baixo e {moves} para a esquerda.',diagram),q(f'Desenhe dois caminhos diferentes de E até D, andando só sobre as linhas da malha. Conte os passos de cada um.',f'Exemplos: direita {moves} e cima {vertical}; ou cima {vertical} e direita {moves}. Ambos têm {moves+vertical} passos; aceitar outros caminhos corretamente contados.',diagram,space='drawing'),q(f'Um robô anda {moves} passos para a direita, {vertical} para cima e {moves} para a esquerda. Onde termina em relação ao início?',f'{vertical} passos acima do início, na mesma coluna.'),q(f'Crie um trajeto da porta até uma mesa em uma sala imaginária. Desenhe ao menos uma mudança de direção e escreva instruções para um colega seguir.',f'Resposta aberta: início e chegada identificados; instruções coerentes com o esboço e pelo menos uma mudança de direção.',space='drawing')]
 if code=='EF02MA13':
  return [q(f'Desenhe uma planta simples de uma {place} vista de cima. Marque entrada, saída e dois objetos do ambiente.',f'Resposta aberta: vista superior, entrada e saída indicadas e dois objetos localizados. Podem coincidir entrada e saída se explicitado.',space='drawing'),q(f'Em uma planta, use P para porta e M para mesa. Coloque a porta embaixo e {n+2} mesas. Faça uma legenda para os símbolos.',f'Planta com P embaixo, {n+2} símbolos M e legenda correta.',space='drawing'),q(f'Desenhe uma sala vista de cima: porta embaixo, janela no alto e armário à direita. Trace um caminho da porta ao armário sem atravessar os móveis.',f'Posições coerentes com os lados da folha e caminho contínuo que contorne os móveis.',space='drawing'),q(f'Uma pessoa desenhou uma planta da {place}, mas esqueceu de marcar a entrada. Por que essa informação faz falta?',f'Sem a entrada, o visitante não sabe por onde começar a se orientar ou entrar no ambiente.'),q(f'Esboce o roteiro entre uma entrada e a {place}. Use uma árvore como ponto de referência e escreva três instruções.',f'Resposta aberta: roteiro com entrada, árvore e destino; três instruções coerentes com o desenho.',space='drawing')]
 if code in ['EF03MA14','EF04MA17','EF05MA16']:
  sides=[3,4,5,6,8][n];shape_names={8:'octogonal',3:'triangular',4:'quadrangular',5:'pentagonal',6:'hexagonal'}
  prism=f'prisma de base {shape_names[sides]}';pyramid=f'pirâmide de base {shape_names[sides]}'
  questions=[q(f'Um {prism} tem duas bases de {sides} lados. Quantas faces laterais e quantas faces no total ele possui?',f'{sides} faces laterais e {sides+2} faces no total.'),q(f'Uma {pyramid} tem uma base. Quantas faces laterais, faces totais e vértices ela possui?',f'{sides} faces laterais triangulares, {sides+1} faces totais e {sides+1} vértices.'),q('Observe a planificação: uma faixa de retângulos e dois polígonos iguais. Que sólido ela forma? Conte as partes.',f'{prism.capitalize()}: {sides} retângulos laterais e duas bases de {sides} lados.',{'type':'net','name':'prisma','sides':sides}),q(f'Compare um {prism} com uma {pyramid}. O que muda no número de bases e nas faces laterais?',f'Prisma: duas bases e {sides} faces laterais; no prisma reto mostrado, são retângulos. Pirâmide: uma base e {sides} faces laterais triangulares.'),q('Observe esta planificação de cubo. Quantos quadrados aparecem? Qual figura plana forma cada face do sólido?', 'Seis quadrados; cada face do cubo é quadrada.',net('cubo'))]
  if code=='EF03MA14':
   questions[1]=q(f'Para montar um cilindro com papel, usamos um retângulo e quantos círculos iguais? Qual parte o retângulo forma?','Dois círculos iguais; o retângulo forma a superfície lateral.',net('cilindro'))
   questions[4]=q('Uma planificação de cone é formada por um círculo e um setor circular (uma parte de círculo). Qual é a base e qual forma a lateral?','O círculo é a base; o setor circular forma a superfície lateral. Não confundir setor com triângulo.')
  return questions
 if code=='EF03MA15':
  arr=[['triângulo','quadrado','retângulo','paralelogramo','trapézio'][((n+i)%5)] for i in range(5)]
  return [q('Conte os lados e vértices de cada figura A, B, C, D e E.', '; '.join(f'{chr(65+i)}: '+('3 lados e 3 vértices' if s=='triângulo' else '4 lados e 4 vértices') for i,s in enumerate(arr))+'.',shapes(arr)),q('Quais figuras desenhadas pertencem ao grupo dos quadriláteros? Explique.',join(chr(65+i) for i,s in enumerate(arr) if s!='triângulo')+'; todas têm quatro lados.',shapes(arr)),q(f'Um estudante diz que todo quadrilátero é quadrado. Use um retângulo de lados {a} cm e {b+1} cm para explicar o erro.',f'Esse retângulo tem quatro lados, mas lados vizinhos de medidas {a} e {b+1}; não é quadrado.'),q('Compare triângulo e trapézio: o que muda na quantidade de lados e vértices?','Triângulo: 3 lados e 3 vértices. Trapézio: 4 lados e 4 vértices.',shapes(['triângulo','trapézio'])),q(f'Desenhe dois quadriláteros de formatos diferentes e marque seus vértices. Escreva uma semelhança entre eles.','Resposta aberta: dois polígonos de quatro lados, com quatro vértices marcados; ambos são quadriláteros.',space='grid')]
 if code=='EF03MA16':
  w=n+2;h=2
  return [q(f'Na malha, desenhe dois retângulos de {w} quadradinhos por {h}, em lugares diferentes. Eles são congruentes?',f'Sim. Têm a mesma forma e as mesmas medidas; mudar a posição não altera a congruência.',space='grid'),q(f'Compare um retângulo de {w} por {h} quadradinhos com outro de {w+1} por {h}. Eles coincidem completamente por sobreposição?',f'Não. Uma das medidas é diferente ({w} e {w+1}).'),q('Observe as duas figuras iguais, uma girada. É possível fazê-las coincidir usando recortes? Como?','Sim: girar e deslocar uma das figuras até sobrepor a outra.',{'type':'rotated','shape':'triângulo','size':w}),q(f'Um quadrado tem lado {a} cm e outro tem lado {2*a} cm. Ter a mesma forma basta para serem congruentes? Explique.','Não. Também precisam ter as mesmas medidas; esses quadrados têm lados diferentes.'),q(f'Desenhe um L usando {n+4} quadradinhos e copie a mesma figura em outra posição. Como verificar a congruência?',f'Resposta aberta: cópia com mesma forma e tamanho; verificar por sobreposição, contagem das casas ou papel transparente.',space='grid')]
 if code=='EF04MA16':
  return [q('Observe o mapa: as ruas A e B são horizontais, e C é vertical. Quais ruas são paralelas? Quais são perpendiculares?', 'A e B são paralelas; C é perpendicular a A e a B.',{'type':'streets','variant':n}),q(f'Um carro segue {a} quadras para a direita na rua A e vira para cima na rua C. A mudança foi para uma rua paralela ou perpendicular?','Perpendicular; as direções horizontal e vertical formam ângulo reto.',{'type':'streets','variant':n}),q('Desenhe duas ruas paralelas e uma rua perpendicular às duas. Nomeie cada rua.','Resposta aberta: duas retas distintas na mesma direção e uma que as cruze formando ângulos retos.',space='grid'),q(f'Uma pessoa vai {a} quadras para leste e {a} para oeste na mesma rua, sem outros movimentos. Onde termina? Houve mudança de sentido?','Retorna ao ponto de partida. Houve mudança de sentido na mesma direção.'),q(f'Desenhe um trajeto com {a} passos para a direita e {b} para cima. Marque o ponto de mudança de direção e explique se os trechos são perpendiculares.',f'Os trechos horizontal e vertical são perpendiculares; o ponto da virada deve estar marcado.',space='grid')]
 if code=='EF04MA18':
  angle=[30,45,60,120,135][n]
  return [q('Qual ângulo desenhado é reto? Como conferir usando o canto de uma folha?', 'A: 90°. Sobrepor o canto reto da folha ao vértice e aos lados.',{'type':'angles','values':[90,angle]}),q(f'Um quadrado de lado {a} cm é girado sobre a mesa. Seus ângulos continuam retos? Explique.','Sim. A rotação não muda a medida dos ângulos.'),q('Desenhe um ângulo reto e um ângulo com abertura menor. Marque o vértice de cada um.','Resposta aberta: um ângulo de 90° e outro entre 0° e 90°, com vértices identificados.',space='drawing'),q('Observe um retângulo. Quantos ângulos retos ele tem? E um triângulo retângulo?', 'Retângulo: quatro. Triângulo retângulo: um.',shapes(['retângulo','triângulo retângulo'])),q(f'Uma abertura de {angle}° é reta, menor que a reta ou maior que a reta? Compare com 90°.',('Menor que a reta.' if angle<90 else 'Maior que a reta.')+f' {angle}° é '+('menor' if angle<90 else 'maior')+' que 90°.')]
 if code=='EF04MA19':
  d=n+1
  return [q(f'A reta vertical tracejada é um espelho. O ponto A está {d} quadradinho{"s" if d>1 else ""} à esquerda dela. Marque A′ do outro lado, na mesma altura.',f'A′ fica {d} quadradinhos à direita do eixo, na mesma linha horizontal.',{'type':'mirror','distance':d},space='drawing'),q('Desenhe um quadrado e trace um eixo de simetria. Como verificar dobrando o papel?','Aceitar eixo vertical, horizontal ou diagonal do quadrado; as duas metades devem coincidir ao dobrar.',space='grid'),q(f'Um retângulo de {a} cm por {b+2} cm tem suas diagonais como eixos de simetria? Explique ou teste com dobradura.','Não. Como não é quadrado, suas diagonais não são eixos de simetria. Os dois eixos passam pelos pontos médios de lados opostos.'),q(f'Desenhe um triângulo à esquerda de uma reta vertical e faça sua imagem refletida à direita. Marque a distância de um par de vértices ao eixo.','Resposta aberta: pares correspondentes à mesma distância perpendicular do eixo, em lados opostos; forma e medidas preservadas.',space='grid'),q('Na reflexão, a figura fica maior? Ela é congruente à original? Justifique.','Não fica maior; é congruente. A reflexão preserva as medidas dos lados e dos ângulos, mudando a orientação.')]
 if code=='EF05MA14':
  col='ABCDE'[n];row=n+2
  return [q(f'Uma planilha usa letras nas colunas e números nas linhas. Qual é o endereço da célula na coluna {col}, linha {row}?',f'{col}{row}.'),q(f'No endereço {col}{row}, o que indica a letra e o que indica o número?',f'{col} indica a coluna; {row} indica a linha.'),q(f'No plano abaixo, identifique as coordenadas de P. Leia primeiro o eixo horizontal e depois o vertical.',f'P = ({a}, {b}).',grid([['P',a,b]],8)),q(f'Marque A({a}, 1) e B(1, {a}). Os dois pontos têm a mesma posição? Por quê?',f'Não. A ordem das coordenadas importa: a primeira é horizontal e a segunda é vertical.',grid(size=8),space='drawing'),q(f'Em um mapa geográfico simplificado, um lugar está em {10+n}° S e {40+n}° O. Qual informação corresponde à latitude e qual à longitude?',f'{10+n}° S é latitude, ao sul da Linha do Equador; {40+n}° O é longitude, a oeste de Greenwich.')]
 if code=='EF05MA15':
  x=n+1;y=2;dx=2;dy=n+1
  return [q(f'Marque P({x}, {y}) no plano. Depois marque Q, que fica {dx} unidades à direita de P. Escreva Q.',f'Q = ({x+dx}, {y}).',grid(size=9),space='drawing'),q(f'Partindo de P({x}, {y}), suba {dy} unidades e ande 2 à direita. Quais são as coordenadas finais?',f'({x+2}, {y+dy}).',grid([['P',x,y]],9)),q(f'Descreva um trajeto de A({x}, 1) até B({x+2}, {dy+1}), usando um deslocamento horizontal e um vertical.',f'2 unidades para a direita e {dy} para cima, em qualquer ordem.',grid([['A',x,1],['B',x+2,dy+1]],9)),q(f'Um robô em ({x}, 2) está voltado para cima. Gira 90° no sentido horário e avança 2 unidades. Onde chega e para onde está voltado?',f'Chega a ({x+2}, 2), voltado para a direita.'),q(f'Desenhe um trajeto que saia de ({x}, 1), forme um retângulo de largura 2 e altura {dy}, e volte ao início. Liste os vértices na ordem.',f'Exemplo: ({x},1), ({x+2},1), ({x+2},{dy+1}), ({x},{dy+1}), ({x},1). Aceitar o sentido inverso.',grid(size=9),space='drawing')]
 if code=='EF05MA17':
  ns=[3,4,5,6,8];sides=ns[n];nom={3:'triângulo',4:'quadrilátero',5:'pentágono',6:'hexágono',8:'octógono'}
  return [q(f'Como se chama um polígono de {sides} lados? Quantos vértices e ângulos internos ele tem?',f'{nom[sides].capitalize()}; {sides} vértices e {sides} ângulos internos.'),q('Por que um círculo não é polígono? Compare com a figura de lados retos.', 'Polígonos são figuras planas fechadas limitadas por segmentos de reta. O círculo tem contorno curvo.',shapes(['círculo',nom[sides]])),q(f'Desenhe um polígono com {sides} lados. Marque seus vértices e confira se todos os lados são segmentos retos.',f'Resposta aberta: figura simples fechada com {sides} segmentos e {sides} vértices.',space='grid'),q('Todo quadrado é retângulo? Todo retângulo é quadrado? Justifique com lados e ângulos.', 'Todo quadrado é retângulo porque tem quatro ângulos retos. Nem todo retângulo é quadrado: seus quatro lados podem não ter a mesma medida.'),q(f'Dois polígonos têm {sides} lados cada. Isso garante que tenham lados e ângulos de mesmas medidas? Explique.', 'Não. A quantidade de lados não determina suas medidas nem as dos ângulos. Aceitar exemplo de dois polígonos de mesmo número de lados, mas formatos ou tamanhos distintos.')]
 if code=='EF05MA18':
  w=n+2;h=2;factor=n+2
  return [q(f'Um retângulo de {w} por {h} quadradinhos será ampliado com fator {factor}. Quais serão as novas medidas?',f'{w*factor} por {h*factor} quadradinhos.'),q(f'Desenhe um retângulo de {w} por {h} casas e uma ampliação com fator 2. Compare os ângulos.',f'Medidas ampliadas: {2*w} por {2*h}; os quatro ângulos continuam retos e são congruentes aos originais.',space='largegrid'),q(f'Um retângulo de {w*factor} cm por {h*factor} cm é reduzido dividindo todos os lados por {factor}. Quais são as medidas finais?',f'{w} cm por {h} cm.'),q(f'Um retângulo de {w} por {h} foi redesenhado com lados {2*w} por {3*h}. É uma ampliação proporcional? Explique.', 'Não. Um par de lados foi multiplicado por 2 e o outro por 3; falta um único fator comum.'),q(f'Um triângulo de lados 3, 4 e 5 cm foi ampliado com fator {factor}. Quais são os novos lados? Seus ângulos também são multiplicados por {factor}?',f'Lados {3*factor}, {4*factor}, {5*factor} cm. Os ângulos permanecem com as mesmas medidas; não são multiplicados.')]
 raise ValueError(code)

def diversify(code,n,qs):
 # Additional task types avoid repeating identical questions across the 5 lists.
 def setq(i,variants):
  item=variants[n]
  qs[i]=q(*item)
 if code=='EF01MA09':
  setq(4,[('Desenhe quatro peças: duas grandes e duas pequenas. Separe pelo tamanho.','Quatro peças com dois tamanhos bem distinguidos; grupos coerentes.',None,'drawing'),('Uma cesta tem botões redondos e quadrados. Desenhe como separar por forma.','Dois grupos, cada um com botões de uma das formas.',None,'drawing'),('Desenhe três lápis de comprimentos diferentes, do menor para o maior.','Três comprimentos visivelmente crescentes.',None,'drawing'),('Separe uma coleção imaginária de brinquedos em duas caixas. Dê um nome para cada caixa e explique a regra.','Critério explícito e consistente; aceitar por forma, tamanho, cor ou outra característica observável.'),('Desenhe dois quadrados grandes, um quadrado pequeno e um círculo grande. Circule só as peças que são grandes e quadradas.','Devem ser circulados apenas os dois quadrados grandes.',None,'drawing')])
 if code=='EF02MA10':
  setq(4,[('Crie uma sequência de seis figuras repetindo um grupo de três. Escreva o grupo escolhido.','Grupo de três figuras repetido duas vezes.',None,'drawing'),('Crie uma sequência de seis movimentos repetindo palma, palma, pé. Qual é a unidade de repetição?','Palma, palma, pé, palma, palma, pé. Unidade: palma, palma, pé.'),('Escreva quatro números que diminuam de 3 em 3. Comece em 20. Descreva a regra.','20, 17, 14, 11; subtrair 3.'),('Invente uma sequência de quatro números que comece em 5 e aumente sempre a mesma quantidade. Diga a regra.','Exemplo: 5, 9, 13, 17; somar 4. Aceitar outras regras com acréscimo constante.'),('Uma pulseira repete conta grande, conta pequena, conta pequena. Desenhe nove contas e indique o grupo repetido.','Três repetições de grande–pequena–pequena.',None,'drawing')])
 if code=='EF04MA14':
  amount=n+2
  qs[4]=q(f'Crie uma igualdade entre uma adição e um número. Subtraia {amount} dos dois membros, sem resultados negativos, e explique por que ela permanece verdadeira.',f'Resposta aberta. Exemplo: 10+5=15; subtrair {amount} dos dois membros resulta em {15-amount}={15-amount}.')
 if code=='EF01MA13':
  setq(1,[('Qual objeto lembra uma esfera: bola ou caixa de sapatos?','A bola.'),('Qual objeto lembra um cilindro: lata ou dado?','A lata.'),('Qual objeto lembra um cone: chapéu de festa pontudo ou bola?','O chapéu pontudo.'),('Qual objeto lembra um bloco retangular: caixa de sapatos ou bola?','A caixa de sapatos.'),('Um dado de faces quadradas lembra um cubo ou uma esfera?','Um cubo.')])
  models=['cilindro','esfera','cone','bloco retangular','cubo']
  qs[3]=q(f'Desenhe um objeto familiar que lembre {models[n]}. Explique a semelhança.',f'Resposta aberta: objeto aproximadamente em forma de {models[n]}, com semelhança visual explicada.',space='drawing')
 if code in ['EF01MA14','EF02MA15']:
  models=['triângulo','quadrado','retângulo','círculo','triângulo']
  if n<4:qs[3]=q(f'Desenhe um {models[n]} pequeno e outro maior. O nome da figura muda com o tamanho?',f'Não. Ambos continuam sendo {models[n]}; aceitar diferenças de tamanho e orientação.',space='drawing')
  else:qs[3]=q('Desenhe um triângulo com a ponta para cima e outro com a ponta para baixo. Conte os lados dos dois.','Ambos têm três lados; a posição não muda o nome.',space='drawing')
 if code in ['EF02MA12','EF03MA12']:
  destinations=['mesa','armário','janela','estante','quadro']
  qs[4]=q(f'Crie um trajeto da porta até um(a) {destinations[n]} em uma sala imaginária. Desenhe ao menos uma mudança de direção e escreva instruções para um colega.',f'Entrada e {destinations[n]} identificados, caminho contínuo e instruções coerentes; ao menos uma mudança de direção.',space='drawing')
 if code=='EF02MA13':
  layouts=[('direita','esquerda'),('esquerda','direita'),('alto','direita'),('embaixo','esquerda'),('direita','alto')]
  window,cabinet=layouts[n]
  qs[2]=q(f'Desenhe uma sala vista de cima: porta no centro da parte de baixo, janela na parte {window if window in ["direita","esquerda"] else ("de cima" if window=="alto" else "de baixo")} da folha e armário na região {cabinet}. Trace um caminho da porta ao armário.',f'Vista superior com porta embaixo, janela na região {window}, armário na região {cabinet} e trajeto coerente.',space='drawing')
 if code in ['EF02MA14','EF03MA13']:
  setq(2,[('Associe: dado; caixa de sapatos; lata. Use cubo, bloco retangular e cilindro.','Dado → cubo; caixa de sapatos → bloco retangular; lata → cilindro.'),('Associe bola e chapéu de festa pontudo aos nomes esfera e cone.','Bola → esfera; chapéu pontudo → cone.'),('Uma caixa cúbica e um dado lembram o mesmo sólido? Diga qual.','Sim, ambos lembram cubo.'),('Um rolo de papel e uma lata lembram cilindros. Cite uma semelhança de forma.','Possuem bases circulares e uma superfície lateral curva, no modelo geométrico aproximado.'),('Uma caixa de leite e uma bola lembram sólidos diferentes. Nomeie os dois.','Caixa de leite → bloco retangular; bola → esfera.')])
  setq(3,[('Uma embalagem tem base quadrada e faces laterais triangulares que se encontram numa ponta. Ela lembra cone ou pirâmide?','Pirâmide de base quadrada.'),('Uma embalagem tem base circular e uma ponta. Ela lembra cone ou pirâmide de base quadrada?','Cone.'),('Qual sólido tem todas as seis faces quadradas: cubo ou cilindro?','Cubo.'),('Compare esfera e cilindro: qual não tem nenhuma face plana?','A esfera. O cilindro tem duas bases planas circulares.'),('Um sólido tem duas bases circulares iguais e uma lateral curva. Qual é o nome?','Cilindro.')])
 if code=='EF03MA14':
  setq(1,[('Para montar um cilindro de papel, um retângulo forma a lateral. Quantos círculos iguais completam as bases?','Dois círculos.'),('Uma planificação de cilindro tem dois círculos de tamanhos diferentes. O que deve ser corrigido?','As duas bases precisam ter o mesmo tamanho no cilindro circular reto.'),('Um cone e um cilindro têm a mesma quantidade de bases? Explique.','Não. O cone tem uma base circular; o cilindro tem duas.'),('Ao abrir apenas a lateral de uma lata cilíndrica em um modelo de papel, qual figura plana se obtém?','Um retângulo.'),('Uma caixa tem duas bases triangulares e três faces laterais retangulares. Ela é cilindro ou prisma?','Prisma triangular: duas bases triangulares e três retângulos laterais.')])
  setq(4,[('Uma planificação de cone tem um círculo e um setor circular. Qual parte é a base e qual é a lateral?','Círculo: base. Setor circular: superfície lateral.'),('Alguém quer fechar um cone de papel usando um quadrado como base. Qual forma deve recortar para a base?','Um círculo, ajustado à abertura do cone.'),('Na planificação de uma pirâmide de base quadrada, que figuras formam a base e as faces laterais?','Um quadrado na base e quatro triângulos laterais.'),('Conte as faces de um cubo e diga que figuras precisam aparecer em sua planificação.','Seis faces; seis quadrados.'),('Um retângulo e dois círculos iguais formam a planificação usual de qual sólido? Por que não é cone?','Cilindro. O cone tem uma base e lateral em forma de setor circular.')])
 if code in ['EF04MA17','EF05MA16']:
  setq(4,[('Uma planificação de cubo tem quantos quadrados?','Seis quadrados.',net('cubo')),('Uma planificação de pirâmide tem um quadrado e quatro triângulos. Quantas faces terá o sólido montado?','Cinco faces: uma base quadrada e quatro faces triangulares.'),('Uma planificação reúne duas bases pentagonais e cinco retângulos. Quantas faces e vértices tem o sólido?','Prisma pentagonal: 7 faces e 10 vértices.'),('Uma pirâmide de base hexagonal terá quantos triângulos na planificação?','Seis triângulos laterais, além da base hexagonal.'),('Uma planificação de prisma tem quatro retângulos laterais e duas bases. Quantos lados tem cada base?','Quatro lados em cada base; trata-se de prisma quadrangular.')])
 if code=='EF03MA15':
  pairs=[('triângulo','trapézio'),('quadrado','triângulo'),('retângulo','paralelogramo'),('trapézio','quadrado'),('paralelogramo','triângulo')]
  x,y=pairs[n]
  qs[3]=q(f'Compare {x} e {y}: conte os lados e os vértices de cada um.',f'{x}: '+('3 lados e 3 vértices' if x=='triângulo' else '4 lados e 4 vértices')+f'; {y}: '+('3 lados e 3 vértices.' if y=='triângulo' else '4 lados e 4 vértices.'),shapes([x,y]))
  qs[4]=q(f'Desenhe um {x} e um {y}. Marque os vértices e explique uma semelhança ou diferença.',f'Figuras coerentes com os nomes. Comparar quantidade de lados/vértices ou características visíveis.',space='grid')
 if code=='EF04MA16':
  qs[2]=q(f'Desenhe {n+2} ruas paralelas e uma rua perpendicular a todas elas. Nomeie as ruas.',f'{n+2} retas paralelas distintas, cruzadas por uma perpendicular que forme ângulos retos.',space='grid')
 if code=='EF04MA18':
  setq(2,[('Desenhe um ângulo reto e um ângulo de abertura menor. Marque os vértices.','Um ângulo de 90° e outro entre 0° e 90°, com vértices marcados.',None,'drawing'),('Use o canto de uma folha para desenhar um ângulo reto. Depois desenhe uma abertura maior.','Ângulo de 90° e outro maior que 90° e menor que 180°.',None,'drawing'),('Desenhe um triângulo que tenha um ângulo reto e marque esse ângulo.','Triângulo retângulo com um ângulo de 90° indicado.',None,'grid'),('Desenhe um quadrilátero com quatro ângulos retos. Marque cada um.','Retângulo ou quadrado, com quatro marcações corretas.',None,'grid'),('Desenhe dois ângulos retos em posições diferentes. O giro muda a abertura?','Não. Ambos conservam 90°.',None,'drawing')])
  setq(3,[('Quantos ângulos retos tem um retângulo? E um triângulo retângulo?','Retângulo: quatro. Triângulo retângulo: um.'),('Um quadrado foi girado até parecer apoiado num vértice. Quantos ângulos retos conserva?','Quatro.'),('Um triângulo poderia ter dois ângulos retos? Explique usando desenho ou dobradura.','Não. Dois ângulos retos já somariam 180°, não restando abertura para um terceiro ângulo de um triângulo.'),('Uma figura tem quatro cantos iguais aos cantos de uma folha de papel. Esses cantos são retos?','Sim, têm abertura de 90°.'),('A abertura de uma volta inteira pode ser dividida em quantos ângulos retos?','Quatro: cada um mede 90°.')])
 if code=='EF04MA19':
  setq(1,[('Desenhe um quadrado e marque um eixo de simetria vertical. Explique a dobra.','Dobra vertical pelo centro; as metades coincidem.',None,'grid'),('Desenhe um quadrado e marque um eixo de simetria horizontal.','Reta horizontal pelo centro do quadrado.',None,'grid'),('Desenhe um retângulo não quadrado e marque seus dois eixos de simetria.','Reta horizontal e reta vertical pelos pontos médios de lados opostos.',None,'grid'),('Desenhe um círculo e marque dois eixos de simetria diferentes.','Quaisquer duas retas distintas passando pelo centro.',None,'drawing'),('Desenhe um triângulo com dois lados iguais e trace um eixo de simetria.','Reta do vértice comum aos lados iguais ao ponto médio da base.',None,'drawing')])
  figure=['triângulo','quadrado','retângulo','figura em L','pentágono'][n]
  qs[3]=q(f'Desenhe um(a) {figure} à esquerda de uma reta vertical e faça sua imagem refletida à direita. Marque a distância de um par de vértices ao eixo.',f'Figura e imagem congruentes, em lados opostos, com vértices correspondentes à mesma distância perpendicular do eixo.',space='grid')
  setq(4,[('Na reflexão, a figura fica maior? Ela é congruente à original?','Não fica maior; a reflexão preserva forma e medidas, produzindo figura congruente.'),('Um ponto está exatamente no eixo de reflexão. Sua imagem muda de lugar?','Não. Pontos do eixo permanecem na mesma posição.'),('Um vértice está a 2 casas do eixo; seu reflexo foi marcado a 3 casas. O desenho está correto?','Não. A imagem deve estar a 2 casas do outro lado, na mesma perpendicular ao eixo.'),('Refletir uma figura duas vezes no mesmo eixo a leva de volta à posição inicial? Explique.','Sim. A segunda reflexão desfaz a primeira; cada ponto retorna à posição original.'),('O reflexo de um segmento de 4 cm pode ter 6 cm? Por quê?','Não. A reflexão preserva o comprimento; o segmento refletido deve medir 4 cm.')])
 if code=='EF05MA17':
  setq(3,[('Todo quadrado é retângulo? Todo retângulo é quadrado? Justifique.','Todo quadrado é retângulo, pois tem quatro ângulos retos. Nem todo retângulo tem os quatro lados iguais.'),('Um polígono com cinco vértices tem quantos lados e quantos ângulos internos?','Cinco lados e cinco ângulos internos.'),('Uma linha quebrada aberta, formada por seis segmentos, é um polígono? Explique.','Não. Para delimitar um polígono, a linha precisa ser fechada e simples.'),('Um losango precisa ter os quatro ângulos retos? O que caracteriza seus lados?','Não. Os quatro lados têm a mesma medida; se tiver quatro ângulos retos, também é quadrado.'),('Um pentágono regular e um pentágono irregular têm a mesma quantidade de lados? O que pode ser diferente?','Ambos têm cinco lados. No regular, lados e ângulos internos são iguais entre si; no irregular, essa igualdade não ocorre para todos.')])
 return qs

bank=[]
for area,fn in [('algebra',algebra),('geometria',geometry)]:
 source=(ROOT/area/'index.html').read_text()
 original=json.JSONDecoder().raw_decode(source.split('const DATA=')[1])[0]
 for year,skills in original.items():
  for skill in skills:
   entry={'area':area,'year':int(year),'code':skill['code'],'description':skill['description'],'lists':[]}
   for n in range(5):
    questions=diversify(skill['code'],n,fn(skill['code'],n))
    assert len(questions)==5
    for i,item in enumerate(questions):item['id']=f'{skill["code"]}-L{n+1}-Q{i+1}'
    entry['lists'].append({'id':f'{skill["code"]}-L{n+1}','number':n+1,'questions':questions})
   bank.append(entry)
assert len(bank)==38
output='/* Fixed authored exercises; rebuild with tools/build-exercise-lists.py. */\nwindow.EXERCISE_BANK = '+json.dumps(bank,ensure_ascii=False,separators=(',',':'))+';\n'
(ROOT/'professor/listas/data.js').write_text(output)
print(f'{len(bank)} habilidades, {len(bank)*5} listas, {len(bank)*25} questões; {len(output.encode())} bytes.')
